algoritmo "Q_20"

var
i, m : Inteiro
inicio
// Seção de Comandos
Escreva("Informe o numero: ")
Leia(m)
i <- 0

Enquanto (i < 10)Faca
   i <- i + 1
   Escreval(i," +",m, " =" ,i+m)
Fimenquanto
i <- 0
Enquanto (i < 10)Faca
   i <- i + 1
   Escreval(i," -",m, " =" ,i-m)
Fimenquanto
i <- 0
Enquanto (i < 10)Faca
   i <- i + 1
   Escreval(i," x",m, " =" ,i*m)
Fimenquanto
i <- 0
Enquanto (i < 10)Faca
   i <- i + 1
   Escreval(i," /",m, " =" ,i/m)
Fimenquanto
fimalgoritmo
